#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kvstore count growth
graph_vlabel keys/s
swingset_kvstore_count.label Swingset KVStore Count Growth Rate
swingset_kvstore_count.draw LINE2
swingset_kvstore_count.type DERIVE
swingset_kvstore_count.min 0
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_kvstore_count.value', data['swingset']['kv']['entries'])
