#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd cosmos state size
graph_vlabel bytes
cosmos_size.label Cosmos State Size
cosmos_size.draw LINE2
cosmos_size.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('cosmos_size.value', data['cosmos']['total'])
