#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd cosmos state size
graph_vlabel bytes
cosmos_size_application.label application.db
cosmos_size_application.draw LINE2
cosmos_size_application.type GAUGE
cosmos_size_blockstore.label blockstore.db
cosmos_size_blockstore.draw LINE2
cosmos_size_blockstore.type GAUGE
cosmos_size_snapshots.label snapshots.db
cosmos_size_snapshots.draw LINE2
cosmos_size_snapshots.type GAUGE
cosmos_size_state.label state.db
cosmos_size_state.draw LINE2
cosmos_size_state.type GAUGE
cosmos_size_tx_index.label tx_index.db
cosmos_size_tx_index.draw LINE2
cosmos_size_tx_index.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('cosmos_size_application.value', data['cosmos']['application'])
print('cosmos_size_blockstore.value', data['cosmos']['blockstore'])
print('cosmos_size_snapshots.value', data['cosmos']['snapshots'])
print('cosmos_size_state.value', data['cosmos']['state'])
print('cosmos_size_tx_index.value', data['cosmos']['tx_index'])
