#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kernel objects
graph_vlabel objects
objects.label Kernel Objects
objects.draw LINE2
objects.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('objects.value', data['kernel_stats']['koids'])
