#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset XS growth
graph_vlabel bytes/s
swingset_xs_size.label Swingset XS Heap Snapshot Growth Rate
swingset_xs_size.draw LINE2
swingset_xs_size.type DERIVE
swingset_xs_size.min 0
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_xs_size.value', data['swingset']['snapshot']['size'])
