#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset bundle table size
graph_vlabel bytes
swingset_bundle_size.label Swingset BundleStore Size
swingset_bundle_size.draw LINE2
swingset_bundle_size.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_bundle_size.value', data['swingset']['bundle']['size'])
