#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset XS heap snapshot size
graph_vlabel bytes
swingset_xs_size.label Swingset XS Heap Snapshot Size
swingset_xs_size.draw LINE2
swingset_xs_size.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_xs_size.value', data['swingset']['snapshot']['size'])
