#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kernel clists
graph_vlabel clists
clists.label Kernel C-List Entries
clists.draw LINE2
clists.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('clists.value', data['kernel_stats']['clists'])
