#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset vats
graph_vlabel vats
size.label Vats
size.draw LINE2
size.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('size.value', data['kernel_stats']['vats'])
