#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd slogfile growth
graph_vlabel bytes/s
slogfile_size.label Slogfile Growth
slogfile_size.draw LINE2
slogfile_size.type DERIVE
slogfile_size.min 0
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('slogfile_size.value', data['slogfile'])
