#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset bundle count
graph_vlabel bundles
swingset_bundle_count.label Swingset Bundle Count
swingset_bundle_count.draw LINE2
swingset_bundle_count.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_bundle_count.value', data['swingset']['bundle']['count'])
