#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kernel syscall rate
graph_vlabel syscalls / s
syscalls.label Kernel Syscall Rate
syscalls.draw LINE2
syscalls.type DERIVE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('syscalls.value', data['kernel_stats']['syscalls'])
