#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kernel promises
graph_vlabel promises
promises.label Kernel Promises
promises.draw LINE2
promises.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('promises.value', data['kernel_stats']['kpids'])
