#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kvstore size
graph_vlabel bytes
swingset_kvstore_size.label Swingset KVStore Size
swingset_kvstore_size.draw LINE2
swingset_kvstore_size.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_kvstore_size.value', data['swingset']['kv']['size'])
