#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset kernel delivery rate
graph_vlabel vat deliveries / s
deliveries.label Kernel Delivery Rate
deliveries.draw LINE2
deliveries.type DERIVE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('deliveries.value', data['kernel_stats']['dispatches'])
