#!/usr/bin/env python3

import sys, json, requests

CONFIG = '''\
graph_title agd swingset XS heap snapshot count
graph_vlabel snapshots
swingset_snapshot_count.label Swingset XS Heap Snapshot Count
swingset_snapshot_count.draw LINE2
swingset_snapshot_count.type GAUGE
'''

if len(sys.argv) > 1 and sys.argv[1] == 'config':
    print(CONFIG.rstrip())
    sys.exit(0)

r = requests.get('http://localhost:30003/data')
data = json.loads(r.content)
print('swingset_snapshot_count.value', data['swingset']['snapshot']['count'])
