
PLUGINS=/etc/munin/plugins

diff:
	diff -u ag0_blockheight $(PLUGINS)/ag0_blockheight
	diff -u ag0_blockheight_rate $(PLUGINS)/ag0_blockheight_rate
	diff -u ag0_lag $(PLUGINS)/ag0_lag
	diff -u ag0_lag_ratio $(PLUGINS)/ag0_lag_ratio
	diff -u agd_cosmos_rate $(PLUGINS)/agd_cosmos_rate
	diff -u agd_cosmos_size $(PLUGINS)/agd_cosmos_size
	diff -u agd_cosmos_size_pieces $(PLUGINS)/agd_cosmos_size_pieces
	diff -u agd_slogfile_rate $(PLUGINS)/agd_slogfile_rate
	diff -u agd_state_rate $(PLUGINS)/agd_state_rate
	diff -u agd_state_size $(PLUGINS)/agd_state_size
	diff -u agd_swingset_bundle_size $(PLUGINS)/agd_swingset_bundle_size
	diff -u agd_swingset_kvstore_rate $(PLUGINS)/agd_swingset_kvstore_rate
	diff -u agd_swingset_kvstore_size $(PLUGINS)/agd_swingset_kvstore_size
	diff -u agd_swingset_kvstore_count $(PLUGINS)/agd_swingset_kvstore_count
	diff -u agd_swingset_kvstore_count_rate $(PLUGINS)/agd_swingset_kvstore_count_rate
	diff -u agd_swingset_num_bundles $(PLUGINS)/agd_swingset_num_bundles
	diff -u agd_swingset_rate $(PLUGINS)/agd_swingset_rate
	diff -u agd_swingset_size $(PLUGINS)/agd_swingset_size
	diff -u agd_swingset_size_pieces $(PLUGINS)/agd_swingset_size_pieces
	diff -u agd_swingset_transcript_rate $(PLUGINS)/agd_swingset_transcript_rate
	diff -u agd_swingset_transcript_size $(PLUGINS)/agd_swingset_transcript_size
	diff -u agd_swingset_xs_rate $(PLUGINS)/agd_swingset_xs_rate
	diff -u agd_swingset_xs_size $(PLUGINS)/agd_swingset_xs_size
	diff -u agd_swingset_xs_snapshots $(PLUGINS)/agd_swingset_xs_snapshots
